sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    mySprite.setPosition(29, 40)
    game.gameOver(false)
})
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
let Duck_joe = sprites.create(img`
    . . . . . . . . . b 5 b . . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 b c 5 5 d 4 c . . 
    . b b b b 5 5 5 b f d d 4 4 4 b 
    . b d 5 b 5 5 b c b 4 4 4 4 b . 
    . . b 5 5 b 5 5 5 4 4 4 4 b . . 
    . . b d 5 5 b 5 5 5 5 5 5 b . . 
    . b d b 5 5 5 d 5 5 5 5 5 5 b . 
    b d d c d 5 5 b 5 5 5 5 5 5 b . 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
let Hunter_Bob = sprites.create(img`
    ........................
    ........................
    .......ff...............
    .....ff22ff.............
    ...fff2222fff...........
    ..fff222222fff..........
    ..fff222222fff..........
    ..feeeeeeeeeeff.........
    .ffe22222222eff.........
    .fffffeeeefffff.........
    fdfefbf44fbfeff.........
    fbfe41fddf14ef..........
    fbffe4dddd4efe..........
    fcfef22222f4e...........
    .ff4f44554f4e...........
    ....ffffffdde...........
    .....ffffedde...........
    ..........ee............
    .........ccc............
    ........cc1cc...........
    .........c1c............
    .........c1c............
    .........c1c............
    .........c1c............
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
Hunter_Bob.follow(Duck_joe)
let Hunter_Jimmy = sprites.create(img`
    ........................
    ........................
    .......ff...............
    .....ff22ff.............
    ...fff2222fff...........
    ..fff222222fff..........
    ..fff222222fff..........
    ..feeeeeeeeeeff.........
    .ffe22222222eff.........
    .fffffeeeefffff.........
    fdfefbf44fbfeff.........
    fbfe41fddf14ef..........
    fbffe4dddd4efe..........
    fcfef22222f4e...........
    .ff4f44554f4e...........
    ....ffffffdde...........
    .....ffffedde...........
    ..........ee............
    .........ccc............
    ........cc1cc...........
    .........c1c............
    .........c1c............
    .........c1c............
    .........c1c............
    `, SpriteKind.Enemy)
Hunter_Jimmy.follow(mySprite)
